name = "neko-omake"
compatibility_date = "2024-08-20"

# 静的アセットをCloudflare Workersで配信
[assets]
directory = "./dist"

# 404時の挙動はデフォルト（404を返す）。
# SPAフォールバックが必要なら下記を有効化し、index.htmlにフォールバックします。
# not_found_handling = "single-page-application"
